spring:
  profiles:
    active: @active-profiles@
  security:
    ignored: "/actuator/**"

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: INFO
      zalando:
        logbook: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"